services:
  app:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile-dev
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - .:/app
  
  db:
    restart: unless-stopped
    image: postgres:16
    # Loads from .env file
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: